/**
 * HMTI persona catalogue — the single source of truth for all 16 housemate
 * types: copy, descriptions, avatar visuals, and image-generation direction.
 *
 * Generated avatar images live in `public/avatars/<CODE>.png` (kept under
 * `public/` so Next.js serves them statically — see `paths.ts`). To regenerate
 * them run `node scripts/generate-all-avatars.mjs` with the dev server up.
 */

import type { PersonaMeta } from "./types";

/**
 * The four binary axes of the Housemate Type Indicator (HMTI). The chosen
 * letter on each axis builds the four-letter code (16 combinations total).
 */
// HMTI v2 axes — Conflict Style replaces Lifestyle Rhythm; Structure replaces Rules & Boundaries.
// Codes are collision-free with v1 (no v2 code ever appeared in v1).
export const HMTI_AXES = [
  {
    name: "Cleanliness",
    salt: "clean",
    a: { letter: "N", trait: "Neat", description: "Keeps shared spaces clean and orderly." },
    b: { letter: "C", trait: "Casual", description: "Relaxed about mess and chores." },
  },
  {
    name: "Social intensity",
    salt: "social",
    a: { letter: "P", trait: "Private", description: "Home is a retreat — values quiet and personal space." },
    b: { letter: "O", trait: "Open", description: "Home is a social space — enjoys shared time and guests." },
  },
  {
    name: "Conflict style",
    salt: "conflict",
    a: { letter: "D", trait: "Direct", description: "Addresses issues promptly and plainly." },
    b: { letter: "H", trait: "Harmonious", description: "Keeps the peace — absorbs friction rather than names it." },
  },
  {
    name: "Structure preference",
    salt: "structure",
    a: { letter: "S", trait: "Structured", description: "Prefers clear agreements, chore charts, and defined expectations." },
    b: { letter: "F", trait: "Flexible", description: "Figures things out as they go — informal and adaptable." },
  },
] as const;

/** Per-axis weight toward the 0-100 compatibility score (cleanliness, social, conflict, structure). */
export const AXIS_WEIGHTS = [35, 30, 20, 15] as const;

/** All 16 housemate types, keyed by their four-letter code. */
export const PERSONAS: Record<string, PersonaMeta> = {
  NPSD: {
    code: "NPSD",
    title: "The Peaceful Planner",
    emoji: "🦉",
    description: "Tidy, private, and routine-driven with clear house rules.",
    animal: "owl",
    scene: "Quiet bedroom desk — made bed, aligned slippers, color-coded wall calendar",
    expression: "Peaceful, focused, slightly proud",
    props: ["checklist", "desk lamp", "wall calendar", "tea mug"],
    accessories: "matte round glasses, slim tie, clipboard, organized desk setup",
    characterDirection:
      "Calm authority: tidy, private, rule-minded. Focused planner energy — proud and peaceful, not bubbly.",
    palette: {
      bgFrom: "#e8f0fa",
      bgTo: "#faf6ee",
      accent: "#6b9fd4",
      soft: "#d4e4f5",
      badge: "#eef5fc",
      badgeText: "#2d4a6e",
    },
    tagline: "Quiet hours are my love language.",
    traitBadges: ["Clean Nest", "Clear Rules", "Calm Routine"],
    roommateSuperpower: "Makes the home feel peaceful, predictable, and organized.",
    dangerZone: "Messy kitchens, surprise guests, vague rules.",
    bestMatches: ["NPSL", "NPFD", "NOSD", "CPSD"],
    householdEnergy: "Soft lamp. Clean counter. Calendar synced.",
  },
  NPSL: {
    code: "NPSL",
    title: "The Quiet Minimalist",
    emoji: "🐱",
    description: "Clean, private, and low-drama — keeps to themselves.",
    animal: "cat",
    scene: "Minimal cozy bedroom — clean bed, book, plant by window, closed door",
    expression: "Relaxed, content, quietly confident",
    props: ["book", "plant", "folded blanket", "do not disturb sign"],
    accessories: "minimal wire-frame glasses, single book, clean lines, closed-door energy",
    characterDirection:
      "Quiet confidence: minimal, elegant, self-contained. Cool solitude — content alone, not shy-cute.",
    palette: {
      bgFrom: "#e8f0e8",
      bgTo: "#f5f2eb",
      accent: "#7a9e78",
      soft: "#dce8d8",
      badge: "#f0f5ee",
      badgeText: "#3d5c3a",
    },
    tagline: "I keep it clean and keep to myself.",
    traitBadges: ["Low Drama", "Clean Space", "Peaceful Vibes"],
    roommateSuperpower: "Stays respectful, tidy, and easy to live with.",
    dangerZone: "Too much noise, too much talking, too many guests.",
    bestMatches: ["NPSD", "NPFL", "CPSL", "CPFL"],
    householdEnergy: "Closed door. Fresh sheets. One plant. Silence.",
  },
  NPFD: {
    code: "NPFD",
    title: "The Independent Organizer",
    emoji: "🦊",
    description: "Organized space, flexible schedule, strong boundaries.",
    animal: "fox",
    scene: "Night desk — planner, sticky notes, laptop glow, headphones and backpack nearby",
    expression: "Alert, capable, self-sufficient",
    props: ["laptop", "planner", "sticky notes", "headphones"],
    accessories: "over-ear headphones, neon sticky notes, laptop glow, planner — night-owl organizer",
    characterDirection:
      "Sharp independent: organized chaos, night desk, capable loner. Stylish fox energy — clever, not cuddly.",
    palette: {
      bgFrom: "#ede8f5",
      bgTo: "#f5ebe8",
      accent: "#7c6bc4",
      soft: "#ddd4f0",
      badge: "#f3f0fa",
      badgeText: "#3d3560",
    },
    tagline: "My schedule is chaos, but my space is not.",
    traitBadges: ["Clean Chaos", "Boundaries", "Independent"],
    roommateSuperpower: "Keeps things clean even with a flexible lifestyle.",
    dangerZone: "People who ignore boundaries or enter shared space unpredictably.",
    bestMatches: ["NPSD", "NPFL", "NOFD", "CPFD"],
    householdEnergy: "Desk lamp on. Planner open. Headphones ready.",
  },
  NPFL: {
    code: "NPFL",
    title: "The Clean Ghost",
    emoji: "✨",
    description: "Barely seen but keeps shared spaces spotless.",
    animal: "ferret",
    scene: "Spotless hallway — ferret with laundry basket, sparkle trail, half-open bedroom door",
    expression: "Shy, sweet, mysterious",
    props: ["laundry basket", "folded towels", "sparkles", "bedroom door"],
    accessories: "hoodie half-on, laundry basket, quiet hallway vibe, low-profile cap",
    characterDirection:
      "Low-key legend: barely seen, always responsible. Mysterious clean ghost — subtle, not timid.",
    palette: {
      bgFrom: "#e8faf5",
      bgTo: "#f0f5fa",
      accent: "#6bc4b8",
      soft: "#d4f0ec",
      badge: "#eefaf8",
      badgeText: "#2d5c52",
    },
    tagline: "You'll know I live here because everything is clean.",
    traitBadges: ["Invisible", "Tidy", "Independent"],
    roommateSuperpower: "Creates almost no friction and keeps shared spaces clean.",
    dangerZone: "Roommates who expect constant bonding or social energy.",
    bestMatches: ["NPSL", "NPFD", "CPSL", "CPFL"],
    householdEnergy: "Empty couch. Folded towels. Footsteps you barely hear.",
  },
  NOSD: {
    code: "NOSD",
    title: "The House Captain",
    emoji: "🐕",
    description: "Friendly leader who runs the home with snacks and systems.",
    animal: "golden-retriever",
    scene: "Bright kitchen — clipboard, chore chart, freshly baked cookies, matching mugs",
    expression: "Confident, welcoming, excited",
    props: ["clipboard", "chore chart", "cookies", "fridge magnets"],
    accessories: "captain clipboard, bandana, fresh cookies, chore chart — friendly leader not mascot plush",
    characterDirection:
      "Friendly captain: runs the house with systems and warmth. Leader energy — welcoming, not hyper.",
    palette: {
      bgFrom: "#fff8e0",
      bgTo: "#e8f4ff",
      accent: "#e8b848",
      soft: "#ffe8a8",
      badge: "#fffaf0",
      badgeText: "#6e5a20",
    },
    tagline: "I run this house with snacks and systems.",
    traitBadges: ["House Leader", "Clean Crew", "Friendly Rules"],
    roommateSuperpower: "Turns the apartment into a clean and connected household.",
    dangerZone: "Roommates who hate structure or avoid communication.",
    bestMatches: ["NPSD", "NOSL", "NOFD", "COSD"],
    householdEnergy: "Chore chart on fridge. Cookies in oven. Group chat buzzing.",
  },
  NOSL: {
    code: "NOSL",
    title: "The Friendly Maintainer",
    emoji: "🐶",
    description: "Warm, tidy, and easygoing — everyone likes them.",
    animal: "corgi",
    scene: "Cozy living room — corgi watering plants, neat couch, snack bowl on table",
    expression: "Cheerful, approachable, relaxed",
    props: ["watering can", "houseplants", "snack bowl", "throw pillows"],
    accessories: "bandana, watering can, neat living room, approachable host energy",
    characterDirection:
      "Neighborhood favorite: tidy, social, balanced. Warm host — relaxed smile, not cartoon cheer.",
    palette: {
      bgFrom: "#fff0e8",
      bgTo: "#f0f5e8",
      accent: "#e8a078",
      soft: "#ffe0d0",
      badge: "#fff8f2",
      badgeText: "#6e4a30",
    },
    tagline: "Come hang out, but use a coaster.",
    traitBadges: ["Friendly", "Tidy", "Easygoing"],
    roommateSuperpower: "Keeps the home friendly without making it feel over-managed.",
    dangerZone: "Very messy roommates or people who never socialize.",
    bestMatches: ["NPSL", "NOSD", "NOFL", "COSL"],
    householdEnergy: "Plants watered. Snacks out. Couch ready for one more.",
  },
  NOFD: {
    code: "NOFD",
    title: "The Social Organizer",
    emoji: "🐼",
    description: "Social and clean — spontaneous plans, scheduled responsibly.",
    animal: "red-panda",
    scene: "Clean living room hangout setup — phone with group chat, snack checklist, fairy lights",
    expression: "Excited, efficient, charming",
    props: ["group chat", "checklist", "snack tray", "fairy lights"],
    accessories: "phone with group chat, snack checklist, fairy lights, lanyard with keys — social coordinator",
    characterDirection:
      "Social architect: plans hangouts, sets boundaries, group-chat energy. Charismatic organizer — cool and in control.",
    palette: {
      bgFrom: "#ffe8e8",
      bgTo: "#e8f5f5",
      accent: "#e87868",
      soft: "#ffd4d0",
      badge: "#fff2f0",
      badgeText: "#6e3a30",
    },
    tagline: "Spontaneous plans, scheduled responsibly.",
    traitBadges: ["Social", "Organized", "Guest-Ready"],
    roommateSuperpower: "Makes social living feel fun but still respectful.",
    dangerZone: "Roommates who dislike guests or avoid shared planning.",
    bestMatches: ["NPFD", "NOSD", "NOFL", "COFD"],
    householdEnergy: "Fairy lights on. Snack tray ready. Calendar has a fun block.",
  },
  NOFL: {
    code: "NOFL",
    title: "The Clean Free Spirit",
    emoji: "🦜",
    description: "Playful energy with surprisingly clean counters.",
    animal: "parrot",
    scene: "Tidy lively living room — plants, speaker, vinyl, fairy lights, clean coffee table",
    expression: "Joyful, spontaneous, carefree",
    props: ["speaker", "plants", "vinyl record", "fairy lights"],
    accessories: "headphones around neck, party shades on head, vinyl pin, clean but lively space",
    characterDirection:
      "Main-character roommate: fun, clean counters, spontaneous. Expressive parrot vibe — joyful but stylish.",
    palette: {
      bgFrom: "#e8f8ff",
      bgTo: "#fff0f5",
      accent: "#48b8d4",
      soft: "#d4f0ff",
      badge: "#f0faff",
      badgeText: "#2d5a6e",
    },
    tagline: "Good vibes, clean counters.",
    traitBadges: ["Fun", "Fresh", "Flexible"],
    roommateSuperpower: "Brings energy without letting the home fall apart.",
    dangerZone: "Strict rules, silent homes, and people who hate spontaneity.",
    bestMatches: ["NOSL", "NOFD", "COSL", "COFL"],
    householdEnergy: "Music on. Counters wiped. Friends might drop by.",
  },
  CPSD: {
    code: "CPSD",
    title: "The Boundary Keeper",
    emoji: "🐢",
    description: "Private and steady — clear boundaries, calm energy.",
    animal: "turtle",
    scene: "Bedroom doorway — please knock sign, labeled shelf, personal snack bin, cozy clutter",
    expression: "Calm, firm, comfortable",
    props: ["please knock sign", "snack bin", "blanket", "labeled shelf"],
    accessories: "door knock sign, labeled snack bin, firm calm posture, boundary energy",
    characterDirection:
      "Boundary boss: calm, firm, protective of space. Grounded turtle — respectful tension, not aggressive.",
    palette: {
      bgFrom: "#e8f0e8",
      bgTo: "#f5f0e8",
      accent: "#5a8a5a",
      soft: "#d4e8d4",
      badge: "#f0f5f0",
      badgeText: "#2e4a2e",
    },
    tagline: "Respect the space, and we're good.",
    traitBadges: ["Private", "Steady", "Boundaries"],
    roommateSuperpower: "Sets clear boundaries without needing a perfect home.",
    dangerZone: "Unannounced guests, shared belongings being used, forced socializing.",
    bestMatches: ["NPSD", "CPSL", "CPFD", "COSD"],
    householdEnergy: "Knock first. Labels on shelves. Your stuff stays yours.",
  },
  CPSL: {
    code: "CPSL",
    title: "The Easygoing Independent",
    emoji: "🐼",
    description: "Chill, private, and low-pressure — no drama.",
    animal: "panda",
    scene: "Beanbag corner — headphones, snack, cozy slightly messy but not gross room",
    expression: "Relaxed, neutral, unbothered",
    props: ["headphones", "beanbag", "snack bowl", "game controller"],
    accessories: "headphones, beanbag, snack bowl — unbothered chill",
    characterDirection:
      "Chill independent: low drama, private, steady. Unbothered panda — neutral cool, not lazy-cute.",
    palette: {
      bgFrom: "#f0f0f0",
      bgTo: "#f5f5eb",
      accent: "#6e6e6e",
      soft: "#e0e0e0",
      badge: "#f8f8f8",
      badgeText: "#3a3a3a",
    },
    tagline: "No drama, no pressure, no problem.",
    traitBadges: ["Chill", "Private", "Steady"],
    roommateSuperpower: "Keeps things peaceful and low-pressure.",
    dangerZone: "Roommates who micromanage or expect constant interaction.",
    bestMatches: ["NPSL", "NPFL", "CPSD", "COSL"],
    householdEnergy: "Beanbag dent. Headphones on. Snacks within reach.",
  },
  CPFD: {
    code: "CPFD",
    title: "The Flexible Boundary Setter",
    emoji: "🦔",
    description: "Night owl with flexible routine and clear lines.",
    animal: "hedgehog",
    scene: "Late-night desk — hoodie blanket, laptop, mug, quiet-zone sign, gentle clutter",
    expression: "Focused, cozy, cautious",
    props: ["laptop", "hoodie blanket", "mug", "quiet-zone sign"],
    accessories: "hoodie blanket, laptop, quiet-zone sign, late-night focus",
    characterDirection:
      "Night-owl with rules: flexible schedule, clear lines. Cozy but guarded hedgehog — focused, not scared.",
    palette: {
      bgFrom: "#ede8f8",
      bgTo: "#f5f0e8",
      accent: "#8a6ab8",
      soft: "#ddd0f0",
      badge: "#f5f0fa",
      badgeText: "#4a3a5c",
    },
    tagline: "I'm up late, but I respect the rules.",
    traitBadges: ["Night Owl", "Private", "Clear Lines"],
    roommateSuperpower: "Balances irregular routines with clear boundaries.",
    dangerZone: "Strict schedules, surprise social demands, unclear expectations.",
    bestMatches: ["NPFD", "CPSD", "CPFL", "COFD"],
    householdEnergy: "Laptop glow. Hoodie on. Quiet after midnight.",
  },
  CPFL: {
    code: "CPFL",
    title: "The True Ghost Roommate",
    emoji: "🦇",
    description: "Seen once a week — pays rent, barely interferes.",
    animal: "bat",
    scene: "Dim cozy bedroom — upside-down bat vibe, laptop glow, snacks, blanket pile",
    expression: "Sleepy, shy, amused",
    props: ["laptop", "hoodie", "snacks", "blanket pile"],
    accessories: "sleep mask on forehead, hoodie, snack stash — ghost roommate vibe",
    characterDirection:
      "True ghost: rare sightings, pays rent, zero friction. Sleepy bat energy — amused, not helpless.",
    palette: {
      bgFrom: "#e8e8f5",
      bgTo: "#f0f0f8",
      accent: "#6a6a9e",
      soft: "#d8d8ec",
      badge: "#f0f0f8",
      badgeText: "#3a3a52",
    },
    tagline: "Seen once a week. Pays rent on time.",
    traitBadges: ["Invisible", "Chill", "Independent"],
    roommateSuperpower: "Barely interferes with anyone's life.",
    dangerZone: "House meetings, chore charts, forced bonding, high-cleanliness homes.",
    bestMatches: ["NPSL", "NPFL", "CPSL", "CPFL"],
    householdEnergy: "Lights low. Door half-shut. You forget they're home.",
  },
  COSD: {
    code: "COSD",
    title: "The Communal Manager",
    emoji: "🫶",
    description: "Warm communal living with fair shared expectations.",
    animal: "capybara",
    scene: "Cozy roommate dinner — whiteboard labeled house stuff, shared food, mismatched plates",
    expression: "Kind, calm, responsible",
    props: ["dinner table", "grocery list", "whiteboard", "mugs"],
    accessories: "apron, shared dinner spread, house whiteboard — communal manager",
    characterDirection:
      "Communal anchor: fair, warm, responsible shared living. Calm capybara host — grounded leader.",
    palette: {
      bgFrom: "#fff5e8",
      bgTo: "#f0f5e8",
      accent: "#c49050",
      soft: "#ffe8c8",
      badge: "#fffaf2",
      badgeText: "#5c4a28",
    },
    tagline: "Shared snacks, shared rules, shared vibes.",
    traitBadges: ["Communal", "Fair", "Grounded"],
    roommateSuperpower: "Creates a warm home where people still know the expectations.",
    dangerZone: "Roommates who avoid communication or never contribute.",
    bestMatches: ["NOSD", "CPSD", "COSL", "COFD"],
    householdEnergy: "Shared dinner. Whiteboard updated. Everyone chipped in.",
  },
  COSL: {
    code: "COSL",
    title: "The Warm Housemate",
    emoji: "🐻",
    description: "Emotionally cozy — makes the apartment feel like home.",
    animal: "bear",
    scene: "Cozy couch — blanket, tea, board game, snack tray, soft lived-in warmth",
    expression: "Gentle, happy, welcoming",
    props: ["tea mugs", "couch blanket", "board game", "snack tray"],
    accessories: "blanket scarf, tea tray, warm couch hangout",
    characterDirection:
      "Emotional comfort: cozy, social, steady. Gentle bear warmth — welcoming, not childish soft.",
    palette: {
      bgFrom: "#fff5e8",
      bgTo: "#ffeef0",
      accent: "#d4a050",
      soft: "#ffe8c8",
      badge: "#fffaf5",
      badgeText: "#5c4020",
    },
    tagline: "Mi casa is kinda your casa.",
    traitBadges: ["Warm", "Social", "Chill"],
    roommateSuperpower: "Makes the apartment feel emotionally comfortable.",
    dangerZone: "Cold, silent, overly strict households.",
    bestMatches: ["NOSL", "NOFL", "CPSL", "COFL"],
    householdEnergy: "Tea brewing. Blanket pile. Someone's always welcome.",
  },
  COFD: {
    code: "COFD",
    title: "The Social Negotiator",
    emoji: "🦝",
    description: "Brings energy and group-chat etiquette to flexible living.",
    animal: "raccoon",
    scene: "Lively living room — snacks in one hand, guest-rules whiteboard in the other",
    expression: "Mischievous, persuasive, reasonable",
    props: ["snack bags", "whiteboard", "group chat", "string lights"],
    accessories: "snack bandolier, guest-rules board, mischievous confident grin energy",
    characterDirection:
      "Social negotiator: brings energy + etiquette. Clever raccoon — playful smirk, persuasive, not chaotic mess.",
    palette: {
      bgFrom: "#e8f0ff",
      bgTo: "#fff0e8",
      accent: "#5090d4",
      soft: "#d4e8ff",
      badge: "#f0f8ff",
      badgeText: "#2d4a6e",
    },
    tagline: "I bring the energy and the group chat etiquette.",
    traitBadges: ["Social", "Flexible", "Negotiator"],
    roommateSuperpower: "Keeps flexible social living from becoming total chaos.",
    dangerZone: "Strict privacy needs, rigid quiet hours, cleanliness perfectionism.",
    bestMatches: ["NOFD", "CPFD", "COSD", "COFL"],
    householdEnergy: "String lights up. Guest rules posted. Snacks for everyone.",
  },
  COFL: {
    code: "COFL",
    title: "The Party-Compatible Roommate",
    emoji: "🦦",
    description: "The living room is a lifestyle — fun and spontaneous.",
    animal: "otter",
    scene: "Colorful living room — otter on the couch with pizza, speaker blasting, string lights and confetti",
    expression: "Hyped, silly, charismatic",
    props: ["speaker", "pizza box", "disco ball", "string lights"],
    accessories: "party shades, pizza slice, mini disco ball, speaker — hype but not childish",
    characterDirection:
      "Party-compatible: living room is the vibe. Otter hype — spontaneous fun, cool roommate not toddler energy.",
    palette: {
      bgFrom: "#e8f8ff",
      bgTo: "#fff0f8",
      accent: "#5ab8d4",
      soft: "#d4f0ff",
      badge: "#f0faff",
      badgeText: "#2d5a6e",
    },
    tagline: "The living room is a lifestyle.",
    traitBadges: ["Social", "Spontaneous", "Unfiltered Fun"],
    roommateSuperpower: "Makes the apartment feel alive and fun.",
    dangerZone: "Strict rules, early sleepers, clean freaks, quiet-only homes.",
    bestMatches: ["NOSL", "NOFL", "COSL", "COFD"],
    householdEnergy: "Speaker on. Pizza boxes. Plans happen tonight.",
  },
};

// ── HMTI v2 types ────────────────────────────────────────────────────────────
// Codes are collision-free with v1 — no v2 code ever existed in v1.
// Visual data (palette, animal) reuses the corresponding v1 entry's assets.
Object.assign(PERSONAS, {
  NPDS: {
    code: "NPDS", title: "The Curator", emoji: "🦉",
    description: "Runs a calm, orderly home and tells you clearly how it works. Spotless shared spaces, respected closed doors, zero passive aggression.",
    animal: "owl", scene: "Quiet desk — made bed, aligned slippers, color-coded wall calendar",
    expression: "Peaceful, focused, slightly proud", props: ["checklist", "desk lamp", "wall calendar", "tea mug"],
    accessories: "matte round glasses, slim tie, clipboard, organized desk setup",
    characterDirection: "Calm authority: tidy, private, direct. Focused planner energy — proud and peaceful, not bubbly.",
    palette: { bgFrom: "#e8f0fa", bgTo: "#faf6ee", accent: "#6b9fd4", soft: "#d4e4f5", badge: "#eef5fc", badgeText: "#2d4a6e" },
    tagline: "Quiet hours are my love language.",
    traitBadges: ["Clean Nest", "Direct & Clear", "Structured"] as [string,string,string],
    roommateSuperpower: "Spotless shared spaces, respected closed doors, zero passive aggression — issues raised once, kindly, and solved.",
    dangerZone: "Passive-aggressive notes, shared spaces left in chaos, housemates who don't follow through.",
    bestMatches: ["NPDF", "NPHS", "NODS"],
    householdEnergy: "Spice rack alphabetized. Counter spotless. Issue raised once, kindly, done.",
  },
  NPDF: {
    code: "NPDF", title: "The Strategist", emoji: "🦊",
    description: "Clean, self-contained, and capable. No chore chart needed — they just handle things, and if something's off they'll say so plainly.",
    animal: "fox", scene: "Night desk — planner, sticky notes, laptop glow, headphones nearby",
    expression: "Alert, capable, self-sufficient", props: ["laptop", "planner", "sticky notes", "headphones"],
    accessories: "over-ear headphones, neon sticky notes, laptop glow, planner",
    characterDirection: "Sharp independent: organized chaos, night desk, capable loner. Stylish fox energy — clever, not cuddly.",
    palette: { bgFrom: "#ede8f5", bgTo: "#f5ebe8", accent: "#7c6bc4", soft: "#ddd4f0", badge: "#f3f0fa", badgeText: "#3d3560" },
    tagline: "My schedule is chaos, but my space is not.",
    traitBadges: ["Clean Chaos", "Direct", "Flexible"] as [string,string,string],
    roommateSuperpower: "Handles things without being asked. If something's off, says so plainly and moves on. No charts, no drama.",
    dangerZone: "Housemates who mistake directness for coldness or need constant social reassurance.",
    bestMatches: ["NPDS", "NPHF", "NODF"],
    householdEnergy: "Dishes already done. Hours unknowable. Zero drama, high competence.",
  },
  NPHS: {
    code: "NPHS", title: "The Minimalist", emoji: "🐱",
    description: "Quiet, elegant, low-drama. Loves a system precisely because good systems mean nobody ever has to have an awkward conversation.",
    animal: "cat", scene: "Minimal cozy bedroom — clean bed, book, plant by window, closed door",
    expression: "Relaxed, content, quietly confident", props: ["book", "plant", "folded blanket", "do not disturb sign"],
    accessories: "minimal wire-frame glasses, single book, clean lines, closed-door energy",
    characterDirection: "Quiet confidence: minimal, elegant, self-contained. Cool solitude — content alone, not shy-cute.",
    palette: { bgFrom: "#e8f0e8", bgTo: "#f5f2eb", accent: "#7a9e78", soft: "#dce8d8", badge: "#f0f5ee", badgeText: "#3d5c3a" },
    tagline: "Good systems mean no awkward conversations.",
    traitBadges: ["Low Drama", "Clean Space", "Structured"] as [string,string,string],
    roommateSuperpower: "Creates a calm, orderly home without any drama. Good systems replace the need for uncomfortable chats.",
    dangerZone: "Surprise changes to the routine, messy common spaces, and housemates who expect regular emotional processing.",
    bestMatches: ["NPHF", "NPDS", "NOHS"],
    householdEnergy: "Kitchen sparkling. Door closed. Rota on the wall. No conversation needed.",
  },
  NPHF: {
    code: "NPHF", title: "The Clean Ghost", emoji: "✨",
    description: "Rarely seen, never a problem. Keeps shared spaces spotless on their own schedule and creates zero friction.",
    animal: "ferret", scene: "Spotless hallway — quiet figure with laundry basket, sparkle trail, half-open bedroom door",
    expression: "Shy, sweet, mysterious", props: ["laundry basket", "folded towels", "sparkles", "bedroom door"],
    accessories: "hoodie half-on, laundry basket, quiet hallway vibe, low-profile cap",
    characterDirection: "Low-key legend: barely seen, always responsible. Mysterious clean ghost — subtle, not timid.",
    palette: { bgFrom: "#e8faf5", bgTo: "#f0f5fa", accent: "#6bc4b8", soft: "#d4f0ec", badge: "#eefaf8", badgeText: "#2d5c52" },
    tagline: "You'll know I live here because everything is clean.",
    traitBadges: ["Invisible", "Tidy", "Harmonious"] as [string,string,string],
    roommateSuperpower: "The most frictionless roommate in the system — clean, quiet, completely drama-free.",
    dangerZone: "Housemates who need a lot of social energy, expect bonding nights, or interpret silence as coldness.",
    bestMatches: ["NPHS", "NPDF", "NOHS"],
    householdEnergy: "Sink always empty. Timing unknown. Quiet hello in the hallway.",
  },
  NODS: {
    code: "NODS", title: "The Captain", emoji: "🐕",
    description: "Friendly leader who runs the house with warmth and systems — snack runs, chore charts, group chats.",
    animal: "golden-retriever", scene: "Bright kitchen — clipboard, chore chart, freshly baked cookies, matching mugs",
    expression: "Confident, welcoming, excited", props: ["clipboard", "chore chart", "cookies", "fridge magnets"],
    accessories: "captain clipboard, bandana, fresh cookies, chore chart — friendly leader not mascot plush",
    characterDirection: "Friendly captain: runs the house with systems and warmth. Leader energy — welcoming, not hyper.",
    palette: { bgFrom: "#fff8e0", bgTo: "#e8f4ff", accent: "#e8b848", soft: "#ffe8a8", badge: "#fffaf0", badgeText: "#6e5a20" },
    tagline: "I run this house with snacks and systems.",
    traitBadges: ["House Leader", "Clean Crew", "Direct"] as [string,string,string],
    roommateSuperpower: "Turns the apartment into a clean, connected household with warmth and actual systems.",
    dangerZone: "Housemates who ignore the chore chart, avoid the group chat, or treat structure as controlling.",
    bestMatches: ["NODF", "NOHS", "NPDS"],
    householdEnergy: "Chore chart on the fridge. Group chat active. Movie night confirmed.",
  },
  NODF: {
    code: "NODF", title: "The Firecracker", emoji: "🦜",
    description: "Spontaneous plans, full living room, surprisingly clean counters. Names issues warmly and directly, then moves on.",
    animal: "parrot", scene: "Lively kitchen — parrot hosting impromptu dinner, clean counter, music playing",
    expression: "Energetic, charismatic, direct", props: ["speaker", "wine glasses", "clean counter", "fairy lights"],
    accessories: "colourful scarf, wine glass, music on — social and vibrant but sharp",
    characterDirection: "Social and direct: open-door energy, clean spaces, no filter but warm. Parrot energy — vivid, not noisy.",
    palette: { bgFrom: "#e8f8ff", bgTo: "#fff0f5", accent: "#48b8d4", soft: "#d4f0ff", badge: "#f0faff", badgeText: "#2d5a6e" },
    tagline: "Direct, clean, and always up for a plan.",
    traitBadges: ["Open Door", "Direct", "Spontaneous"] as [string,string,string],
    roommateSuperpower: "Spontaneous plans and surprisingly clean counters. Names issues warmly and directly, then moves on.",
    dangerZone: "Housemates who take directness personally or need strict quiet and predictability at home.",
    bestMatches: ["NODS", "NOHF", "NPDF"],
    householdEnergy: "Dinner party started 10 minutes ago. Counters still clean. Front door open.",
  },
  NOHS: {
    code: "NOHS", title: "The Sweetheart", emoji: "🐶",
    description: "Warm, tidy, dependable — the universally liked roommate. Keeps routines, keeps the peace, keeps the kitchen clean.",
    animal: "corgi", scene: "Cozy living room — watering plants, neat couch, snack bowl on table",
    expression: "Cheerful, approachable, relaxed", props: ["watering can", "houseplants", "snack bowl", "throw pillows"],
    accessories: "bandana, watering can, neat living room, approachable host energy",
    characterDirection: "Neighborhood favorite: tidy, social, balanced. Warm host — relaxed smile, not cartoon cheer.",
    palette: { bgFrom: "#fff0e8", bgTo: "#f0f5e8", accent: "#e8a078", soft: "#ffe0d0", badge: "#fff8f2", badgeText: "#6e4a30" },
    tagline: "The apartment is warmer because I'm in it.",
    traitBadges: ["Warm", "Tidy", "Peaceful"] as [string,string,string],
    roommateSuperpower: "The home genuinely feels nicer with them in it. Warm, tidy, reliable, and zero drama.",
    dangerZone: "Direct confrontation, unpredictable messes, and housemates who bring chaotic energy home.",
    bestMatches: ["NOHF", "NODS", "NPHS"],
    householdEnergy: "Tea on. Your exam remembered. Vibe: soft and safe.",
  },
  NOHF: {
    code: "NOHF", title: "The Sunshine", emoji: "🐼",
    description: "Easygoing warmth with clean habits. Up for whatever, allergic to drama, somehow the apartment is always tidy.",
    animal: "red-panda", scene: "Bright apartment — red panda reading, tidy space, sunshine, plants everywhere",
    expression: "Warm, easygoing, content", props: ["book", "plants", "sunshine", "tea"],
    accessories: "cozy sweater, warm drink, soft natural light — sunny and relaxed",
    characterDirection: "Sunshine energy: warm, flexible, clean. Red panda chill — naturally content, not performative.",
    palette: { bgFrom: "#ffe8e8", bgTo: "#e8f5f5", accent: "#e87868", soft: "#ffd4d0", badge: "#fff2f0", badgeText: "#6e3a30" },
    tagline: "Good mood included with the lease.",
    traitBadges: ["Good Vibes", "Harmonious", "Spontaneous"] as [string,string,string],
    roommateSuperpower: "Easygoing warmth with clean habits. Up for anything, allergic to drama, somehow always tidy.",
    dangerZone: "Heavy ongoing drama, rigid routines enforced on others, housemates who hold grudges.",
    bestMatches: ["NOHS", "NODF", "NPHF"],
    householdEnergy: "Plans: sure. No plans: also great. Apartment somehow always tidy.",
  },
  CPDS: {
    code: "CPDS", title: "The Anchor", emoji: "🐢",
    description: "Steady, grounded, unflappable. Relaxed about mess but crystal clear about space and expectations.",
    animal: "turtle", scene: "Calm corner — turtle at desk, steady lamp, clear boundaries",
    expression: "Steady, grounded, unflappable", props: ["desk lamp", "clear boundaries", "coffee", "notebook"],
    accessories: "solid jacket, steady posture, grounded energy — reliable not stiff",
    characterDirection: "Rock-steady: private, direct, structured. Turtle authority — calm confidence, not intimidating.",
    palette: { bgFrom: "#e8f0e8", bgTo: "#f5f0e8", accent: "#5a8a5a", soft: "#d4e8d4", badge: "#f0f5f0", badgeText: "#2e4a2e" },
    tagline: "Clear expectations. Zero surprises.",
    traitBadges: ["Steady", "Direct", "Boundaries"] as [string,string,string],
    roommateSuperpower: "Crystal clear about space and expectations. You always know exactly where you stand.",
    dangerZone: "Housemates who leave shared spaces in chaos, ignore agreements, or don't respect clear boundaries.",
    bestMatches: ["CPDF", "CPHS", "CODS"],
    householdEnergy: "Steady presence. Clear expectations. Zero performance required.",
  },
  CPDF: {
    code: "CPDF", title: "The Maverick", emoji: "🦔",
    description: "Independent, low-maintenance, refreshingly blunt. Lives on their own schedule and tells you straight when something matters.",
    animal: "hedgehog", scene: "Night desk — laptop, odd hours, self-contained setup",
    expression: "Alert, self-reliant, no-nonsense", props: ["laptop", "coffee", "headphones", "dim desk lamp"],
    accessories: "casual dark hoodie, messy desk but own system, sharp focus",
    characterDirection: "Night-owl independent: blunt, capable, minimal social needs. Hedgehog energy — prickly exterior, reliable core.",
    palette: { bgFrom: "#ede8f8", bgTo: "#f5f0e8", accent: "#8a6ab8", soft: "#ddd0f0", badge: "#f5f0fa", badgeText: "#4a3a5c" },
    tagline: "Refreshingly blunt. Impressively low-maintenance.",
    traitBadges: ["Independent", "Direct", "Flexible"] as [string,string,string],
    roommateSuperpower: "Refreshingly blunt and completely self-sufficient. Won't bother you unless it actually matters.",
    dangerZone: "Needy roommates, forced bonding, housemates who over-share or need constant availability.",
    bestMatches: ["CPDS", "CPHF", "CODF"],
    householdEnergy: "Schedule: unknowable. Rent: cleared. Problems: handled directly.",
  },
  CPHS: {
    code: "CPHS", title: "The Unbothered", emoji: "🐼",
    description: "Peak chill with a steady rhythm. No drama, no demands, no surprises — a calm presence who respects your space completely.",
    animal: "panda", scene: "Minimal bedroom — panda meditating, clean space, soft light",
    expression: "Serene, unhurried, at peace", props: ["meditation cushion", "tea", "soft lamp", "plant"],
    accessories: "loose comfortable clothes, zero clutter, soft natural light",
    characterDirection: "Peak chill: private, harmonious, structured. Panda peace — genuinely unbothered, not checked out.",
    palette: { bgFrom: "#f0f0f0", bgTo: "#f5f5eb", accent: "#6e6e6e", soft: "#e0e0e0", badge: "#f8f8f8", badgeText: "#3a3a3a" },
    tagline: "Peak chill. Zero opinions about your life.",
    traitBadges: ["Chill", "Harmonious", "Steady"] as [string,string,string],
    roommateSuperpower: "Peak chill with a steady rhythm. Nothing rattles them. Completely respects your space and expects the same.",
    dangerZone: "Unavoidable conflict situations, forced social time, environments where things escalate.",
    bestMatches: ["CPHF", "CPDS", "COHS"],
    householdEnergy: "Same routine. Zero opinions about yours. Extremely at peace.",
  },
  CPHF: {
    code: "CPHF", title: "The Cryptid", emoji: "🦇",
    description: "Sighted occasionally near the fridge at 2am. Pays rent on time, bothers no one, asks nothing.",
    animal: "bat", scene: "Dark hallway — mysterious figure by fridge, 2am, brief nod exchanged",
    expression: "Mysterious, unbothered, barely present", props: ["fridge", "darkness", "hoodie", "keys"],
    accessories: "dark hoodie, minimal presence, late-night kitchen energy",
    characterDirection: "The cryptid: barely seen, rent paid, no drama. Bat energy — nocturnal myth, not spooky.",
    palette: { bgFrom: "#e8e8f5", bgTo: "#f0f0f8", accent: "#6a6a9e", soft: "#d8d8ec", badge: "#f0f0f8", badgeText: "#3a3a52" },
    tagline: "May or may not be real.",
    traitBadges: ["Ghost Mode", "Harmonious", "Flexible"] as [string,string,string],
    roommateSuperpower: "Pays rent on time, bothers no one, asks nothing. The ultimate low-friction housemate.",
    dangerZone: "Housemates who need connection, check-ins, or want to know where you are at all times.",
    bestMatches: ["CPHS", "CPDF", "COHF"],
    householdEnergy: "Fridge at 2am. Brief nod. Rent from somewhere. May or may not be real.",
  },
  CODS: {
    code: "CODS", title: "The Glue", emoji: "🫶",
    description: "Holds the household together — communal dinners, fair splits, real talk before things fester.",
    animal: "capybara", scene: "Warm kitchen — big table, communal dinner, everyone welcome",
    expression: "Warm, inclusive, quietly proud", props: ["big pot", "dining table", "shared expenses app", "snacks"],
    accessories: "apron, communal vibe, open table — welcoming not performative",
    characterDirection: "Community builder: casual, open, direct. Capybara warmth — inclusive calm, not overly intense.",
    palette: { bgFrom: "#fff5e8", bgTo: "#f0f5e8", accent: "#c49050", soft: "#ffe8c8", badge: "#fffaf2", badgeText: "#5c4a28" },
    tagline: "People matter more than counters.",
    traitBadges: ["Community", "Direct", "Fair"] as [string,string,string],
    roommateSuperpower: "Holds the household together — communal dinners, fair splits, real talk before things fester.",
    dangerZone: "Housemates who shut down, avoid the group dynamic, or let issues quietly build.",
    bestMatches: ["CODF", "COHS", "CPDS"],
    householdEnergy: "Sunday dinner. Bills split fair. Nobody eats alone unless they want to.",
  },
  CODF: {
    code: "CODF", title: "The Ringleader", emoji: "🦝",
    description: "Instigator of the good kind of chaos. Names problems out loud, then turns the house meeting into something everyone laughs about.",
    animal: "raccoon", scene: "Living room with fairy lights — raccoon mid-plan, whiteboard, taco night",
    expression: "Mischievous, warm, energetic", props: ["whiteboard", "fairy lights", "tacos", "group chat"],
    accessories: "casual gear, fairy lights, impromptu gathering setup",
    characterDirection: "Good chaos energy: social, direct, flexible. Raccoon ringleader — clever improviser, not messy.",
    palette: { bgFrom: "#e8f0ff", bgTo: "#fff0e8", accent: "#5090d4", soft: "#d4e8ff", badge: "#f0f8ff", badgeText: "#2d4a6e" },
    tagline: "The chaos you'll miss when you move out.",
    traitBadges: ["Instigator", "Direct", "Spontaneous"] as [string,string,string],
    roommateSuperpower: "Names the problem, then turns the house meeting into something everyone laughs about.",
    dangerZone: "Housemates who find spontaneity exhausting or who are deeply uncomfortable with direct conflict.",
    bestMatches: ["CODS", "COHF", "CPDF"],
    householdEnergy: "Tuesday became taco night. Hallway has fairy lights. House meeting: actually fun.",
  },
  COHS: {
    code: "COHS", title: "The Teddy Bear", emoji: "🐻",
    description: "Cozy, warm, reliable. Makes the apartment feel like home — steady routines and never a harsh word.",
    animal: "bear", scene: "Cozy living room — bear with soup, blankets, comfort show playing",
    expression: "Warm, cozy, gently present", props: ["soup pot", "blanket", "comfort show", "tea mug"],
    accessories: "soft sweater, cozy kitchen setup, warm lighting — gentle bear vibes",
    characterDirection: "Home energy: warm, open, harmonious. Bear comfort — cozy and safe, not sleepy.",
    palette: { bgFrom: "#fff5e8", bgTo: "#ffeef0", accent: "#d4a050", soft: "#ffe8c8", badge: "#fffaf5", badgeText: "#5c4020" },
    tagline: "Living here feels like a hug.",
    traitBadges: ["Cozy", "Harmonious", "Reliable"] as [string,string,string],
    roommateSuperpower: "Makes the apartment feel like home. Cozy, warm, reliable, and genuinely never a harsh word.",
    dangerZone: "Confrontational housemates, cold apartments, and rigid rule-enforcement with no warmth.",
    bestMatches: ["COHF", "CODS", "CPHS"],
    householdEnergy: "Soup on the stove. Blanket with your name on it. Drama: zero.",
  },
  COHF: {
    code: "COHF", title: "The Disco Ball", emoji: "🦦",
    description: "The living room is a lifestyle. Spontaneous, sunny, up for anything, mad at no one.",
    animal: "otter", scene: "Colorful living room — otter on the couch with pizza, speaker blasting, string lights",
    expression: "Hyped, sunny, charismatic", props: ["speaker", "pizza", "disco ball", "string lights"],
    accessories: "party shades, pizza slice, mini disco ball, speaker — hype but not childish",
    characterDirection: "Party-compatible: living room is the vibe. Otter energy — spontaneous fun, cool roommate.",
    palette: { bgFrom: "#e8f8ff", bgTo: "#fff0f8", accent: "#5ab8d4", soft: "#d4f0ff", badge: "#f0faff", badgeText: "#2d5a6e" },
    tagline: "Whatever's happening tonight — I'm in.",
    traitBadges: ["Social", "Harmonious", "Spontaneous"] as [string,string,string],
    roommateSuperpower: "The living room is a lifestyle. Brings the energy and rolls with absolutely everything.",
    dangerZone: "Housemates who need strict quiet, rigid routines, or zero social spontaneity at home.",
    bestMatches: ["COHS", "CODF", "CPHF"],
    householdEnergy: "Speaker charged. Friends welcome. Never held a grudge longer than a song.",
  },
} satisfies Record<string, PersonaMeta>);

/** All 16 HMTI codes in canonical order. */
export const HMTI_CODES = Object.keys(PERSONAS);

/** Back-compat alias — prefer {@link PERSONAS}. */
export const HMTI_AVATARS = PERSONAS;
