/** HMTI Animal Avatar System — visual + copy for all 16 roommate types. */

export type HmtiAvatarMeta = {
  title: string;
  animal: string;
  scene: string;
  expression: string;
  props: string[];
  palette: {
    bgFrom: string;
    bgTo: string;
    accent: string;
    soft: string;
    badge: string;
    badgeText: string;
  };
  tagline: string;
  traitBadges: [string, string, string];
  roommateSuperpower: string;
  dangerZone: string;
  bestMatches: string[];
  householdEnergy: string;
};

export const HMTI_AVATARS: Record<string, HmtiAvatarMeta> = {
  NPSD: {
    title: "The Peaceful Planner",
    animal: "owl",
    scene: "Quiet bedroom desk — made bed, aligned slippers, color-coded wall calendar",
    expression: "Peaceful, focused, slightly proud",
    props: ["checklist", "desk lamp", "wall calendar", "tea mug"],
    palette: {
      bgFrom: "#e8f0fa",
      bgTo: "#faf6ee",
      accent: "#6b9fd4",
      soft: "#d4e4f5",
      badge: "#eef5fc",
      badgeText: "#2d4a6e",
    },
    tagline: "Quiet hours are my love language.",
    traitBadges: ["Clean Nest", "Clear Rules", "Calm Routine"],
    roommateSuperpower: "Makes the home feel peaceful, predictable, and organized.",
    dangerZone: "Messy kitchens, surprise guests, vague rules.",
    bestMatches: ["NPSL", "NPFD", "NOSD", "CPSD"],
    householdEnergy: "Soft lamp. Clean counter. Calendar synced.",
  },
  NPSL: {
    title: "The Quiet Minimalist",
    animal: "cat",
    scene: "Minimal cozy bedroom — clean bed, book, plant by window, closed door",
    expression: "Relaxed, content, quietly confident",
    props: ["book", "plant", "folded blanket", "do not disturb sign"],
    palette: {
      bgFrom: "#e8f0e8",
      bgTo: "#f5f2eb",
      accent: "#7a9e78",
      soft: "#dce8d8",
      badge: "#f0f5ee",
      badgeText: "#3d5c3a",
    },
    tagline: "I keep it clean and keep to myself.",
    traitBadges: ["Low Drama", "Clean Space", "Peaceful Vibes"],
    roommateSuperpower: "Stays respectful, tidy, and easy to live with.",
    dangerZone: "Too much noise, too much talking, too many guests.",
    bestMatches: ["NPSD", "NPFL", "CPSL", "CPFL"],
    householdEnergy: "Closed door. Fresh sheets. One plant. Silence.",
  },
  NPFD: {
    title: "The Independent Organizer",
    animal: "fox",
    scene: "Night desk — planner, sticky notes, laptop glow, headphones and backpack nearby",
    expression: "Alert, capable, self-sufficient",
    props: ["laptop", "planner", "sticky notes", "headphones"],
    palette: {
      bgFrom: "#ede8f5",
      bgTo: "#f5ebe8",
      accent: "#7c6bc4",
      soft: "#ddd4f0",
      badge: "#f3f0fa",
      badgeText: "#3d3560",
    },
    tagline: "My schedule is chaos, but my space is not.",
    traitBadges: ["Clean Chaos", "Boundaries", "Independent"],
    roommateSuperpower: "Keeps things clean even with a flexible lifestyle.",
    dangerZone: "People who ignore boundaries or enter shared space unpredictably.",
    bestMatches: ["NPSD", "NPFL", "NOFD", "CPFD"],
    householdEnergy: "Desk lamp on. Planner open. Headphones ready.",
  },
  NPFL: {
    title: "The Clean Ghost",
    animal: "ferret",
    scene: "Spotless hallway — ferret with laundry basket, sparkle trail, half-open bedroom door",
    expression: "Shy, sweet, mysterious",
    props: ["laundry basket", "folded towels", "sparkles", "bedroom door"],
    palette: {
      bgFrom: "#e8faf5",
      bgTo: "#f0f5fa",
      accent: "#6bc4b8",
      soft: "#d4f0ec",
      badge: "#eefaf8",
      badgeText: "#2d5c52",
    },
    tagline: "You'll know I live here because everything is clean.",
    traitBadges: ["Invisible", "Tidy", "Independent"],
    roommateSuperpower: "Creates almost no friction and keeps shared spaces clean.",
    dangerZone: "Roommates who expect constant bonding or social energy.",
    bestMatches: ["NPSL", "NPFD", "CPSL", "CPFL"],
    householdEnergy: "Empty couch. Folded towels. Footsteps you barely hear.",
  },
  NOSD: {
    title: "The House Captain",
    animal: "golden-retriever",
    scene: "Bright kitchen — clipboard, chore chart, freshly baked cookies, matching mugs",
    expression: "Confident, welcoming, excited",
    props: ["clipboard", "chore chart", "cookies", "fridge magnets"],
    palette: {
      bgFrom: "#fff8e0",
      bgTo: "#e8f4ff",
      accent: "#e8b848",
      soft: "#ffe8a8",
      badge: "#fffaf0",
      badgeText: "#6e5a20",
    },
    tagline: "I run this house with snacks and systems.",
    traitBadges: ["House Leader", "Clean Crew", "Friendly Rules"],
    roommateSuperpower: "Turns the apartment into a clean and connected household.",
    dangerZone: "Roommates who hate structure or avoid communication.",
    bestMatches: ["NPSD", "NOSL", "NOFD", "COSD"],
    householdEnergy: "Chore chart on fridge. Cookies in oven. Group chat buzzing.",
  },
  NOSL: {
    title: "The Friendly Maintainer",
    animal: "corgi",
    scene: "Cozy living room — corgi watering plants, neat couch, snack bowl on table",
    expression: "Cheerful, approachable, relaxed",
    props: ["watering can", "houseplants", "snack bowl", "throw pillows"],
    palette: {
      bgFrom: "#fff0e8",
      bgTo: "#f0f5e8",
      accent: "#e8a078",
      soft: "#ffe0d0",
      badge: "#fff8f2",
      badgeText: "#6e4a30",
    },
    tagline: "Come hang out, but use a coaster.",
    traitBadges: ["Friendly", "Tidy", "Easygoing"],
    roommateSuperpower: "Keeps the home friendly without making it feel over-managed.",
    dangerZone: "Very messy roommates or people who never socialize.",
    bestMatches: ["NPSL", "NOSD", "NOFL", "COSL"],
    householdEnergy: "Plants watered. Snacks out. Couch ready for one more.",
  },
  NOFD: {
    title: "The Social Organizer",
    animal: "red-panda",
    scene: "Clean living room hangout setup — phone with group chat, snack checklist, fairy lights",
    expression: "Excited, efficient, charming",
    props: ["group chat", "checklist", "snack tray", "fairy lights"],
    palette: {
      bgFrom: "#ffe8e8",
      bgTo: "#e8f5f5",
      accent: "#e87868",
      soft: "#ffd4d0",
      badge: "#fff2f0",
      badgeText: "#6e3a30",
    },
    tagline: "Spontaneous plans, scheduled responsibly.",
    traitBadges: ["Social", "Organized", "Guest-Ready"],
    roommateSuperpower: "Makes social living feel fun but still respectful.",
    dangerZone: "Roommates who dislike guests or avoid shared planning.",
    bestMatches: ["NPFD", "NOSD", "NOFL", "COFD"],
    householdEnergy: "Fairy lights on. Snack tray ready. Calendar has a fun block.",
  },
  NOFL: {
    title: "The Clean Free Spirit",
    animal: "parrot",
    scene: "Tidy lively living room — plants, speaker, vinyl, fairy lights, clean coffee table",
    expression: "Joyful, spontaneous, carefree",
    props: ["speaker", "plants", "vinyl record", "fairy lights"],
    palette: {
      bgFrom: "#e8f8ff",
      bgTo: "#fff0f5",
      accent: "#48b8d4",
      soft: "#d4f0ff",
      badge: "#f0faff",
      badgeText: "#2d5a6e",
    },
    tagline: "Good vibes, clean counters.",
    traitBadges: ["Fun", "Fresh", "Flexible"],
    roommateSuperpower: "Brings energy without letting the home fall apart.",
    dangerZone: "Strict rules, silent homes, and people who hate spontaneity.",
    bestMatches: ["NOSL", "NOFD", "COSL", "COFL"],
    householdEnergy: "Music on. Counters wiped. Friends might drop by.",
  },
  CPSD: {
    title: "The Boundary Keeper",
    animal: "turtle",
    scene: "Bedroom doorway — please knock sign, labeled shelf, personal snack bin, cozy clutter",
    expression: "Calm, firm, comfortable",
    props: ["please knock sign", "snack bin", "blanket", "labeled shelf"],
    palette: {
      bgFrom: "#e8f0e8",
      bgTo: "#f5f0e8",
      accent: "#5a8a5a",
      soft: "#d4e8d4",
      badge: "#f0f5f0",
      badgeText: "#2e4a2e",
    },
    tagline: "Respect the space, and we're good.",
    traitBadges: ["Private", "Steady", "Boundaries"],
    roommateSuperpower: "Sets clear boundaries without needing a perfect home.",
    dangerZone: "Unannounced guests, shared belongings being used, forced socializing.",
    bestMatches: ["NPSD", "CPSL", "CPFD", "COSD"],
    householdEnergy: "Knock first. Labels on shelves. Your stuff stays yours.",
  },
  CPSL: {
    title: "The Easygoing Independent",
    animal: "panda",
    scene: "Beanbag corner — headphones, snack, cozy slightly messy but not gross room",
    expression: "Relaxed, neutral, unbothered",
    props: ["headphones", "beanbag", "snack bowl", "game controller"],
    palette: {
      bgFrom: "#f0f0f0",
      bgTo: "#f5f5eb",
      accent: "#6e6e6e",
      soft: "#e0e0e0",
      badge: "#f8f8f8",
      badgeText: "#3a3a3a",
    },
    tagline: "No drama, no pressure, no problem.",
    traitBadges: ["Chill", "Private", "Steady"],
    roommateSuperpower: "Keeps things peaceful and low-pressure.",
    dangerZone: "Roommates who micromanage or expect constant interaction.",
    bestMatches: ["NPSL", "NPFL", "CPSD", "COSL"],
    householdEnergy: "Beanbag dent. Headphones on. Snacks within reach.",
  },
  CPFD: {
    title: "The Flexible Boundary Setter",
    animal: "hedgehog",
    scene: "Late-night desk — hoodie blanket, laptop, mug, quiet-zone sign, gentle clutter",
    expression: "Focused, cozy, cautious",
    props: ["laptop", "hoodie blanket", "mug", "quiet-zone sign"],
    palette: {
      bgFrom: "#ede8f8",
      bgTo: "#f5f0e8",
      accent: "#8a6ab8",
      soft: "#ddd0f0",
      badge: "#f5f0fa",
      badgeText: "#4a3a5c",
    },
    tagline: "I'm up late, but I respect the rules.",
    traitBadges: ["Night Owl", "Private", "Clear Lines"],
    roommateSuperpower: "Balances irregular routines with clear boundaries.",
    dangerZone: "Strict schedules, surprise social demands, unclear expectations.",
    bestMatches: ["NPFD", "CPSD", "CPFL", "COFD"],
    householdEnergy: "Laptop glow. Hoodie on. Quiet after midnight.",
  },
  CPFL: {
    title: "The True Ghost Roommate",
    animal: "bat",
    scene: "Dim cozy bedroom — upside-down bat vibe, laptop glow, snacks, blanket pile",
    expression: "Sleepy, shy, amused",
    props: ["laptop", "hoodie", "snacks", "blanket pile"],
    palette: {
      bgFrom: "#e8e8f5",
      bgTo: "#f0f0f8",
      accent: "#6a6a9e",
      soft: "#d8d8ec",
      badge: "#f0f0f8",
      badgeText: "#3a3a52",
    },
    tagline: "Seen once a week. Pays rent on time.",
    traitBadges: ["Invisible", "Chill", "Independent"],
    roommateSuperpower: "Barely interferes with anyone's life.",
    dangerZone: "House meetings, chore charts, forced bonding, high-cleanliness homes.",
    bestMatches: ["NPSL", "NPFL", "CPSL", "CPFL"],
    householdEnergy: "Lights low. Door half-shut. You forget they're home.",
  },
  COSD: {
    title: "The Communal Manager",
    animal: "capybara",
    scene: "Cozy roommate dinner — whiteboard labeled house stuff, shared food, mismatched plates",
    expression: "Kind, calm, responsible",
    props: ["dinner table", "grocery list", "whiteboard", "mugs"],
    palette: {
      bgFrom: "#fff5e8",
      bgTo: "#f0f5e8",
      accent: "#c49050",
      soft: "#ffe8c8",
      badge: "#fffaf2",
      badgeText: "#5c4a28",
    },
    tagline: "Shared snacks, shared rules, shared vibes.",
    traitBadges: ["Communal", "Fair", "Grounded"],
    roommateSuperpower: "Creates a warm home where people still know the expectations.",
    dangerZone: "Roommates who avoid communication or never contribute.",
    bestMatches: ["NOSD", "CPSD", "COSL", "COFD"],
    householdEnergy: "Shared dinner. Whiteboard updated. Everyone chipped in.",
  },
  COSL: {
    title: "The Warm Housemate",
    animal: "bear",
    scene: "Cozy couch — blanket, tea, board game, snack tray, soft lived-in warmth",
    expression: "Gentle, happy, welcoming",
    props: ["tea mugs", "couch blanket", "board game", "snack tray"],
    palette: {
      bgFrom: "#fff5e8",
      bgTo: "#ffeef0",
      accent: "#d4a050",
      soft: "#ffe8c8",
      badge: "#fffaf5",
      badgeText: "#5c4020",
    },
    tagline: "Mi casa is kinda your casa.",
    traitBadges: ["Warm", "Social", "Chill"],
    roommateSuperpower: "Makes the apartment feel emotionally comfortable.",
    dangerZone: "Cold, silent, overly strict households.",
    bestMatches: ["NOSL", "NOFL", "CPSL", "COFL"],
    householdEnergy: "Tea brewing. Blanket pile. Someone's always welcome.",
  },
  COFD: {
    title: "The Social Negotiator",
    animal: "raccoon",
    scene: "Lively living room — snacks in one hand, guest-rules whiteboard in the other",
    expression: "Mischievous, persuasive, reasonable",
    props: ["snack bags", "whiteboard", "group chat", "string lights"],
    palette: {
      bgFrom: "#e8f0ff",
      bgTo: "#fff0e8",
      accent: "#5090d4",
      soft: "#d4e8ff",
      badge: "#f0f8ff",
      badgeText: "#2d4a6e",
    },
    tagline: "I bring the energy and the group chat etiquette.",
    traitBadges: ["Social", "Flexible", "Negotiator"],
    roommateSuperpower: "Keeps flexible social living from becoming total chaos.",
    dangerZone: "Strict privacy needs, rigid quiet hours, cleanliness perfectionism.",
    bestMatches: ["NOFD", "CPFD", "COSD", "COFL"],
    householdEnergy: "String lights up. Guest rules posted. Snacks for everyone.",
  },
  COFL: {
    title: "The Party-Compatible Roommate",
    animal: "otter",
    scene: "Colorful living room — otter on the couch with pizza, speaker blasting, string lights and confetti",
    expression: "Hyped, silly, charismatic",
    props: ["speaker", "pizza box", "disco ball", "string lights"],
    palette: {
      bgFrom: "#e8f8ff",
      bgTo: "#fff0f8",
      accent: "#5ab8d4",
      soft: "#d4f0ff",
      badge: "#f0faff",
      badgeText: "#2d5a6e",
    },
    tagline: "The living room is a lifestyle.",
    traitBadges: ["Social", "Spontaneous", "Unfiltered Fun"],
    roommateSuperpower: "Makes the apartment feel alive and fun.",
    dangerZone: "Strict rules, early sleepers, clean freaks, quiet-only homes.",
    bestMatches: ["NOSL", "NOFL", "COSL", "COFD"],
    householdEnergy: "Speaker on. Pizza boxes. Plans happen tonight.",
  },
};

export function getHmtiAvatarMeta(code: string): HmtiAvatarMeta {
  return HMTI_AVATARS[code] ?? HMTI_AVATARS.NPSD;
}
